slam_toolbox:
  ros__parameters:

    use_sim_time: true

    slam_mode: mapping

    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    resolution: 0.05
    max_laser_range: 10.0

    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2

    transform_publish_period: 0.02
